// build-gallery — regenerates every preview row in gallery.html from the
// ACTUAL output of statusline.sh, so the gallery always shows terminal truth.
//
// Renders all 27 designs against the two gallery sample payloads (calm / high
// use), converts the ANSI to HTML via ansi2html.js, and rewrites the PREVIEWS
// block in gallery.html between the PREVIEWS:BEGIN / PREVIEWS:END markers.
//
// Run after ANY change to a design in statusline.sh:  node tools/build-gallery.js
"use strict";
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");
const { ansi2html } = require("./ansi2html");

const root = path.join(__dirname, "..");
const engine = path.join(root, "statusline.sh");
const galleryFile = path.join(root, "gallery.html");

// temp git repos so the branch segment renders like the samples
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "slgal-"));
const repo = (state, branch) => {
  const dir = path.join(tmp, state, "directory"); // basename "directory" = the sample dir name
  fs.mkdirSync(dir, { recursive: true });
  const git = (...a) => execFileSync("git", ["-C", dir, ...a], { stdio: ["ignore", "pipe", "pipe"] });
  git("init", "-q", "-b", branch);
  git("-c", "user.email=t@t", "-c", "user.name=t", "commit", "-q", "--allow-empty", "-m", "init");
  return dir;
};

// Fixed clock + reset times so the "5h resets in (Xh Ym)" countdown renders a
// deterministic value every rebuild (no per-minute git churn). REF is the
// injected "now"; each state's resets_at is REF plus a plausible window.
const REF = 1_700_000_000; // fixed epoch seconds
const RESET = { calm: REF + (4 * 3600 + 55 * 60), hot: REF + (2 * 3600 + 13 * 60) };
const payload = (dir, ctx, h5, d7, cost, durMs, add, del, resetAt) => JSON.stringify({
  model: { display_name: "Opus 4.8" },
  workspace: { current_dir: dir },
  context_window: { used_percentage: ctx },
  rate_limits: { five_hour: { used_percentage: h5, resets_at: resetAt }, seven_day: { used_percentage: d7 } },
  cost: { total_cost_usd: cost, total_duration_ms: durMs, total_lines_added: add, total_lines_removed: del },
});

const SAMPLES = {
  calm: payload(repo("calm", "main"), 4, 1, 0, 0.23, 120000, 0, 0, RESET.calm),
  hot: payload(repo("hot", "release/1.2"), 88, 71, 92, 3.10, 2820000, 612, 208, RESET.hot),
};

const previews = {};
for (let n = 1; n <= 27; n++) {
  previews[n] = {};
  for (const [state, input] of Object.entries(SAMPLES)) {
    const out = execFileSync("bash", [engine], {
      input, env: { ...process.env, STATUSLINE_DESIGN: String(n), STATUSLINE_NOW: String(REF * 1000) },
    }).toString().replace(/\r?\n$/, "");
    if (!out) throw new Error(`design ${n} ${state}: empty output`);
    previews[n][state] = ansi2html(out);
  }
}
fs.rmSync(tmp, { recursive: true, force: true });

const gallery = fs.readFileSync(galleryFile, "utf8");
const BEGIN = "// PREVIEWS:BEGIN (generated by tools/build-gallery.js — do not hand-edit)";
const END = "// PREVIEWS:END";
const iB = gallery.indexOf(BEGIN), iE = gallery.indexOf(END);
if (iB === -1 || iE === -1) throw new Error("PREVIEWS markers not found in gallery.html");
const block = BEGIN + "\nconst PREVIEWS = " + JSON.stringify(previews, null, 1) + ";\n" + END;
fs.writeFileSync(galleryFile, gallery.slice(0, iB) + block + gallery.slice(iE + END.length));
console.log("gallery.html previews regenerated for all 27 designs");
